spring:
  application:
    name: api-gateway-netty

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:8081'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

      routes:
        - id: dollar-user
          uri: http://localhost:8082
          predicates:
            - Path=/users/**

        - id: dollar-product
          uri: http://localhost:8083
          predicates:
            - Path=/products/**,/admin/products/**

        - id: dollar-order
          uri: http://localhost:8084
          predicates:
            - Path=/order/**,/payment/**

        - id: dollar-review
          uri: http://localhost:8085
          predicates:
            - Path=/products/{productId}/reviews/**



server:
  port: 80

jwt.key: ${jwt.secret.key}