spring:
  application:
    name: api-gateway-netty

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalCors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${cors.url}
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

      routes:
        - id: dollar-user
          uri: ${load.user}
          predicates:
            - Path=/users/**

        - id: dollar-review
          uri: ${load.review}
          predicates:
            - Path=/products/{productId}/reviews/**

        - id: dollar-product
          uri: ${load.product}
          predicates:
            - Path=/products/**,/admin/products/**

        - id: dollar-order
          uri: ${load.order}
          predicates:
            - Path=/order/**,/payment/**




server:
  port: 8080

jwt:
  key: ${jwt.secret.key}